export const researchCollections = [
    { id: 'servers', title: { ko: '서버 조사와 데이터', en: 'Server research and data', ja: 'サーバー調査とデータ' },
      description: { ko: '관측 시점·표본·산정 공식을 밝힌 분석부터 읽고 현재 데이터와 비교하세요.', en: 'Read dated analyses with sample definitions and methods, then compare current observations.', ja: '観測時点・標本・算定方法を確認してから、現在のデータと比較できます。' },
      posts: ['2026-09-08-001-Server-Status', '2026-06-30-001-Server-Tier'],
      tools: ['/information/data/servers', '/information/data/overall', '/information/data/realpower', '/history/ssc-2026'],
      matches: ['/information/data', '/history/'] },
    { id: 'combat', title: { ko: '전투 공식과 실측', en: 'Combat formulas and experiments', ja: '戦闘式と実測' },
      description: { ko: '추정 공식과 실험 결과를 구분하고, 원본 피해량과 조건을 확인합니다.', en: 'Separate hypotheses from measurements and inspect damage values and experimental conditions.', ja: '推定式と実験結果を分け、元のダメージ値と実験条件を確認します。' },
      posts: ['2026-07-04-001-Damage3','2026-07-02-002-Damage2','2026-07-02-003-Damage3','2026-07-02-001-Damage','2026-03-06-002-Attack-speed'],
      tools: ['/information/kartz'], matches: ['/information/kartz'] },
    { id: 'growth', title: { ko: '성장과 장비', en: 'Progression and equipment', ja: '育成と装備' },
      description: { ko: '장비의 작동 방식과 선택 기준을 읽고, 도구에서 필요한 자원과 조건을 확인하세요.', en: 'Read equipment mechanics and decision criteria, then check costs and assumptions in the tools.', ja: '装備の仕組みと選択基準を読み、ツールで必要資源と条件を確認できます。' },
      posts: ['2026-08-20-002-Titan-Refine','2026-08-20-001-Chip-Specialization','2026-03-06-001-HT-Chips','2026-03-04-001-Heavy-Trooper'],
      tools: ['/simulator/titan-refine','/simulator/titan-research','/simulator/formation-perk','/calculator/cost','/calculator/skill','/calculator/value-pack','/information/job','/information/appearance'],
      matches: ['/simulator/','/calculator/cost','/calculator/skill','/calculator/value-pack','/information/job'] },
    { id: 'strategy', title: { ko: '전장과 공략', en: 'Battlefields and guides', ja: '戦場と攻略' },
      description: { ko: '전장별 규칙과 실제 선택 상황을 살펴보고 필요한 계산으로 이어갑니다.', en: 'Explore battlefield rules and concrete decisions, with links to relevant calculations.', ja: '戦場ごとのルールと判断を確認し、必要な計算につなげます。' },
      posts: ['2026-09-10-001-Kartz-Diamond-Buffs','2026-08-20-003-SvS','2026-08-18-001-Titan-Canyon','2026-05-10-001-Storm-eye-battle','2026-05-09-001-World-Boss'],
      tools: ['/information/el','/information/el/darkforce','/information/el/score','/calculator/vital','/information/kartz'],
      matches: ['/information/el','/calculator/vital'] },
];
